name: Healthcheck

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 17 * * *"

jobs:
  healthcheck_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-empty-forest-2749.fly.dev
          max-attempts: 3
          retry-delay: 5s

      - name: Healthcheck pass
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
                -X POST \
                -d '{"content": "Periodic health check passes"}' \
                ${{ secrets.DISCORD_WEBHOOK }}
    
      - name: Healthcheck fail
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
                -X POST \
                -d '{"content": "Health check failed"}' \
                ${{ secrets.DISCORD_WEBHOOK }}